/**
 * src/config/appConfig.js
 *
 * Single source of truth for all app-level static configuration.
 * Import individual exports — never import the whole file as a blob.
 *
 * Fields that change per environment (API keys, feature flags) live in
 * src/config/features.js and src/config/premium.js.
 * App version and changelog live in src/config/version.js.
 */

// ── Identity ──────────────────────────────────────────────────────────────

export const APP_NAME         = 'TaxFreely'
export const APP_TAGLINE      = 'Global Tax Calculator for Freelancers & Employees'
export const APP_DOMAIN       = 'https://taxfreely.com'
export const APP_PACKAGE_ID   = 'com.taxfreely.app'

// ── Contact ────────────────────────────────────────────────────────────────

export const SUPPORT_EMAIL    = 'support@taxfreely.com'
export const FEEDBACK_EMAIL   = 'feedback@taxfreely.com'
export const LEGAL_EMAIL      = 'legal@taxfreely.com'
export const LEGAL_COMPANY    = 'TaxFreely'
export const LEGAL_EFFECTIVE  = '2026-01-01'

// ── Store links (update after listing goes live) ──────────────────────────

export const PLAY_STORE_URL   = 'https://play.google.com/store/apps/details?id=com.taxfreely.app'
export const APP_STORE_URL    = 'https://apps.apple.com/app/taxfreely/id0000000000'
export const WEB_PLUS_URL     = 'https://taxfreely.gumroad.com/l/plus'
export const REVIEW_PLAY_URL  = 'market://details?id=com.taxfreely.app'
export const REVIEW_WEB_URL   = 'https://play.google.com/store/apps/details?id=com.taxfreely.app&showAllReviews=true'

// ── Social links ──────────────────────────────────────────────────────────

export const SOCIAL = {
  twitter:  'https://twitter.com/taxfreely',
  github:   'https://github.com/taxfreely',
}

// ── Employment types ──────────────────────────────────────────────────────

export const EMPLOYMENT_TYPES = {
  EMPLOYEE:     'employee',
  SELF_EMPLOYED:'self_employed',
  FREELANCER:   'freelancer',
  CONTRACTOR:   'contractor',
}

export const EMPLOYMENT_TYPE_LABELS = {
  employee:     'Employee',
  self_employed:'Self-Employed',
  freelancer:   'Freelancer',
  contractor:   'Contractor',
}

export const DEFAULT_EMPLOYMENT_TYPE = EMPLOYMENT_TYPES.EMPLOYEE

// ── Defaults ──────────────────────────────────────────────────────────────

export const DEFAULT_COUNTRY_CODE   = 'US'
export const DEFAULT_CURRENCY_CODE  = 'USD'
export const DEFAULT_LANGUAGE       = 'en'

// ── Data limits ───────────────────────────────────────────────────────────

export const MAX_HISTORY_ITEMS      = 100
export const MAX_SAVED_PROFILES     = 10
export const MAX_COMPARISON_COUNTRIES = 5   // used in CountryComparison.jsx

// ── Tax calculation settings ──────────────────────────────────────────────

/** Income streams supported in the multi-income calculator */
export const MAX_INCOME_STREAMS     = 5

/** Deduction categories (9 total, all free) */
export const DEDUCTION_CATEGORIES = [
  { id: 'home_office',    label: 'Home Office' },
  { id: 'equipment',      label: 'Equipment & Hardware' },
  { id: 'software',       label: 'Software & Subscriptions' },
  { id: 'transport',      label: 'Transport & Travel' },
  { id: 'professional',   label: 'Professional Development' },
  { id: 'health',         label: 'Health & Insurance' },
  { id: 'pension',        label: 'Pension & Retirement' },
  { id: 'marketing',      label: 'Marketing & Advertising' },
  { id: 'other',          label: 'Other Business Expenses' },
]

/** VAT registration nudge threshold — show if income within 20% of threshold */
export const VAT_NUDGE_MARGIN       = 0.80

// ── Quarterly payment defaults ────────────────────────────────────────────

/** Default quarterly dates used when country has quarterlyPayments: true
    but no specific dates supplied */
export const DEFAULT_QUARTERLY_DATES = ['03-31', '06-30', '09-30', '12-31']

// ── PDF / export ──────────────────────────────────────────────────────────

export const PDF_FOOTER         = `Estimated by ${APP_NAME} · ${APP_DOMAIN}`
export const PDF_PLUS_FOOTER    = `Generated by ${APP_NAME} Plus · ${APP_DOMAIN}`
export const PDF_DISCLAIMER_SHORT =
  'Estimates only. Consult a qualified tax professional for your situation.'

// ── Full disclaimer (shown in Disclaimer.jsx and ToS) ────────────────────

export const DISCLAIMER =
  `${APP_NAME} provides tax estimates for informational purposes only. ` +
  'Results do not constitute legal, financial, or tax advice. ' +
  'Tax laws change frequently and vary by individual circumstance. ' +
  'Always verify with your local tax authority or a qualified tax professional ' +
  'before making financial decisions.'

// ── Receipt scanner ───────────────────────────────────────────────────────

/** Supported image types for OCR upload */
export const RECEIPT_ACCEPTED_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/heic']

/** Max file size in bytes for receipt upload (10 MB) */
export const RECEIPT_MAX_SIZE_BYTES = 10 * 1024 * 1024

// ── Cache / storage keys ──────────────────────────────────────────────────

export const STORAGE_KEYS = {
  TERMS_ACCEPTED:   'tf_terms_accepted',
  LANGUAGE:         'tf_language',
  THEME:            'tf_theme',
  CURRENCY:         'tf_currency',
  LAST_COUNTRY:     'tf_last_country',
  HISTORY:          'tf_history',
  PROFILES:         'tf_profiles',
  PLUS_STATUS:      'tf_plus_status',
  RATES_CACHE:      'tf_rates_cache',
  RATES_TIMESTAMP:  'tf_rates_ts',
  ONBOARDING_DONE:  'tf_onboarding_done',
  REVIEW_SHOWN:     'tf_review_shown',
  APP_VERSION_SEEN: 'tf_version_seen',
}

/** Live exchange rate cache TTL in milliseconds (24 hours) */
export const RATES_CACHE_TTL_MS = 24 * 60 * 60 * 1000
